### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ToriTim** [alexnew1999/Hybrid-Warfare-Strategy#2]
Hello!
I really like your idea. If you haven't finished yet, is there any chance, I can contribute to your project?
Here is how I can be helpful:

C++/C# coding (just keep in mind, that I don't know a lot of things yet)
Translation of the story in following languages, if needed: Ukrainian, German, Russian.

**Comment by alexnew1999** [comment]
Hello!

Thank you for reaching out and expressing interest in contributing to my project. I am thrilled to hear that you like my idea!

Your skills in C++/C# coding would be invaluable to my project, even if you're still learning.

I would be delighted to have you on board! Please let me know how you would like to get involved, and I'll provide you with more information on how you can contribute effectively. Here is my email alexnew19999@gmail.com

Looking forward to working together!
